# Generated by Django 3.2.20 on 2023-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kakaonickname',
            field=models.CharField(max_length=30),
        ),
    ]
