# Generated by Django 3.2.20 on 2023-11-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_customuser_kakaonickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.TextField()),
                ('order_id', models.TextField()),
                ('order_date', models.DateTimeField()),
                ('create_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_info', models.TextField()),
                ('is_used', models.BooleanField()),
                ('used_at', models.DateTimeField()),
                ('create_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('nickname', models.TextField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.payinfo')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.ticket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.user')),
            ],
        ),
    ]
